# Generated by Django 4.1.3 on 2022-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='imgurl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png', max_length=128),
        ),
    ]
