# Generated by Django 4.1.3 on 2022-12-03 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_listing_delete_bids_delete_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imgurl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', max_length=512),
        ),
    ]
